[package]
name = "nutcracker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nutcracker"
test = false
bench = false

[dependencies]
log = "0.4.22"
uefi = { version = "0.30.0", features = ["panic_handler", "logger"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

