set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_SYSTEM_VERSION 0.0.0.1)

find_program(CMAKE_C_COMPILER clang REQUIRED)
find_program(CMAKE_CXX_COMPILER clang++ REQUIRED)
find_program(CMAKE_ASM_COMPILER clang REQUIRED)

set(CMAKE_SYSROOT ${CMAKE_SOURCE_DIR}/SystemRoot)

set(CMAKE_C_FLAGS "-target x86_64-saturnos" CACHE STRING "Flags for compilation of C source" FORCE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
